set_a = (1, 2, 3, 4)
set_b = (3, 4, 5, 6)
print("Union:", set_a | set_b)
print("Intersection:", set_a & set_b)
print("Difference (A - B):", set_a - set_b)
set_a.add(10)
print("After adding 10 to A:", set_a)
set_a.remove(3)
print("After removing 3 from A:", set_a)
set_a.discard(8)
print("After discarding 8 from A:", set_a)
